services:
  egaite_web:
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - "4000"           # expose to other containers, but no host binding
    depends_on:
      - db
    restart: always
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - POOL_SIZE=${POOL_SIZE}
      - SECRET_KEY_BASE=${SECRET_KEY_BASE}
      - PHX_HOST=${PHX_HOST}
      - PORT=${PORT}
      - DNS_CLUSTER_QUERY=${DNS_CLUSTER_QUERY}

  nginx:
    image: nginx:latest
    ports:
      - "8082:80"
    depends_on:
      - egaite_web
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    restart: always

  db:
    image: postgres:17.5
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    restart: always

volumes:
  pgdata:
