services:
  egaite_web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    depends_on:
      - db
    restart: always
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - POOL_SIZE=${POOL_SIZE}
      - SECRET_KEY_BASE=${SECRET_KEY_BASE}
      - PHX_HOST=${PHX_HOST}
      - PORT=${PORT}
      - DNS_CLUSTER_QUERY=${DNS_CLUSTER_QUERY}

  db:
    image: postgres:17.5
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    restart: always

volumes:
  pgdata:
